package dk.allanmc.cuesdk.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * contains information about led and its color<br>
 * <i>native declaration : target\CUESDK\include\CUESDK.h:97</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CorsairLedColor extends Structure {
	/**
	 * @see CorsairLedId<br>
	 * identifier of LED to set<br>
	 * C type : CorsairLedId
	 */
	public int ledId;
	/** red   brightness[0..255] */
	public int r;
	/** green brightness[0..255] */
	public int g;
	/** blue  brightness[0..255] */
	public int b;
	public CorsairLedColor() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("ledId", "r", "g", "b");
	}
	/**
	 * @param ledId @see CorsairLedId<br>
	 * identifier of LED to set<br>
	 * C type : CorsairLedId<br>
	 * @param r red   brightness[0..255]<br>
	 * @param g green brightness[0..255]<br>
	 * @param b blue  brightness[0..255]
	 */
	public CorsairLedColor(int ledId, int r, int g, int b) {
		super();
		this.ledId = ledId;
		this.r = r;
		this.g = g;
		this.b = b;
	}
	public CorsairLedColor(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends CorsairLedColor implements Structure.ByReference {
		
	};
	public static class ByValue extends CorsairLedColor implements Structure.ByValue {
		
	};
}
